local X11 = require("x11")
local dpy <close> = X11.connect()
print(string.format("root: %d", dpy.root))
print(string.format("screen: %d", dpy.screen))
print(dpy.foo)
print(dpy[0])

print(dpy.xrandr.version)
print(dpy.xrandr.version)
print(dpy.xrandr.version)
