name: Tests
on:
  push:
  schedule:
    - cron: "* * 7 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Build
      run: make build

    - name: Check README.md
      run: tools/is-clean --make --root=doc README.md
